### ISSUE TITLE
Trigger aggregation and save result to another model

### ISSUE THREAD

**Issue by q-user** [wesleykendall/django-pgtrigger-tutorial#1]
Hello! I just learned about PostgreSQL triggers, and found out this repository. My task is calculate average score across the table on create, update or delete and save result to another table. Is this possible with django-pgtrigger?

**Comment by wesleykendall** [comment]
@q-user yes, you will need to use raw SQL for this use case though! If you need further help, feel free to open a question on the django-pgtrigger repo
